version: 2.1
jobs:
  build-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: npm run test
      - run: npm run build

workflows:
  node-tests:
    jobs:
      - build-test
